spring.application.name=delivery
spring.datasource.url=jdbc:mysql://localhost:3307/db_kulinermedan
spring.datasource.username=root
spring.datasource.password=wesly@21
spring.jpa.hibernate.ddl-auto=update